### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by rogemus** [AdobeDocs/uxp-photoshop#99] opened 2020-10-30 16:15 UTC
**Page**:  `/src/pages/guides/uxp_guide/uxp-toolchain/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-toolchain/#installing-the-tooling
**Link text**: `instructions here`

**Page**:  `/src/pages/guides/uxp_guide/uxp-toolchain/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-toolchain/#batchplay-logger-for-extendscript-developers
**Link text**: `ExtendScript BatchPlay logger`

**Page**:  `/src/pages/guides/uxp_for_you/uxp_for_extendscript_devs/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_for_you/uxp_for_extendscript_devs/#different-dom-access
**Link text**: `Photoshop API page`

**Page**:  `/src/pages/guides/uxp_for_you/uxp_for_extendscript_devs/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_for_you/uxp_for_extendscript_devs/#whats-missing-in-uxp
**Link text**: `this document`

**Page**:  `/src/pages/guides/uxp_for_you/uxp_for_extendscript_devs/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_for_you/uxp_for_extendscript_devs/#whats-missing-in-uxp
**Link text**: `this document`

**Page**:  `/src/pages/guides/uxp_guide/uxp-misc/file-access/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-misc/file-access/#overview
**Link text**: `Networking`

**Page**:  `/src/pages/guides/uxp_guide/uxp-misc/file-access/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-misc/file-access/#overview
**Link text**: `Secure Storage`

**Page**:  `in /src/pages/guides/debugging/index.md`
**Section**: https://www.adobe.io/photoshop/uxp/guides/debugging/#installation-problems
**Link text**: `UXP Developer Tool`

**Comment by chuckweger** [comment] 2020-11-12 01:21
These will be fixed in Sprint 2:
#1: fixed
#2: could not reproduce (link to batchPlay logger works)
#3: fixed
#4: fixed
#5: dupe of #4
#6: fixed, although the Networking section is a placeholder at the moment.
#7: fixed (removed link)
#8: fixed.

Thanks for your extensive link review!

**Closed** 2020-11-18 20:32 UTC

**Comment by thejustinwalsh** [comment] 2021-06-05 00:03
re: Batchplay logger (https://github.com/adobe-uxp/ps-es-to-uxp)
This is a 404 on my Github account. Is the logger behind some permissions that the public is not able to access?

**Comment by ErinFinnegan** [comment] 2021-06-10 22:16
I've just asked asked @baaygun ...

**Comment by RicheekaBathija** [comment] 2021-09-20 04:17
Any updates on this?
